### ISSUE TITLE
DataCamp3 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3851-Fall2019/datacamp3-bobbyregan#1]
@bobbyregan 

* The references for Breiman’s Random Forest and Kuhn’s Caret will need to be individually adjusted in the *.bib file.  Once manual changes are made, either comment out the code or use eval = FALSE in the code chunk that creates the *.bib file.

The rest looks great!

**Comment by bobbyregan** [comment]
@alanarnholt I've gone back over it and believe I've got it now

**Comment by alanarnholt** [comment]
@bobbyregan Great....closing now.
